# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required 

addons:
  apt:
    packages:
      - libgdal1-dev 
      - libproj-dev 
      - libxml2-dev
      - libcurl4-openssl-dev

notifications:
  email:
    on_success: change
    on_failure: change
